server:
  port: 8001
  servlet:
    context-path: /

spring:
  security:
    oauth2:
      client:
        registration:
          chzzk:
            client-id: 7118939e-061b-4ad3-b4b3-bb0cb2432931
            client-secret: KVsdi_hTL5DgKAqoznIjUNDIqoTjIPIw2kVshrZu1Rc
            scope:
              - "ìœ ì €%20ì •ë³´%20ì¡°íšŒ"
              - "í›„ì›%20ì¡°íšŒ"
              - "êµ¬ë…%20ì¡°íšŒ"
              - "ì±„íŒ…%20ë©”ì‹œì§€%20ì¡°íšŒ"
              - "ì±„ë„%20ì •ë³´%20ì¡°íšŒ"
            redirect-uri: "http://localhost:8001/login/oauth2/code/chzzk"
            authorization-grant-type: authorization_code
        provider:
          chzzk:
            # ğŸš¨ (í•„ìˆ˜) ì´ URIë“¤ë„ ì¹˜ì§€ì§ ë¡œê·¸ì¸ìš© ê³µì‹ URIì—¬ì•¼ í•©ë‹ˆë‹¤.
            authorization-uri: https://chzzk.naver.com/oauth/authorize
            token-uri: https://chzzk.naver.com/oauth/token
            user-info-uri: https://api.chzzk.naver.com/service/v1/user/user-info
            user-name-attribute: userId # (ì˜ˆì‹œ)